query getStoreConfig {
    storeConfig {
        base_link_url
        base_media_url
        base_static_url
        base_url
        catalog_default_sort_by
        code
        copyright
        header_logo_src
        locale
        logo_alt
        logo_height
        logo_width
        header_logo_src
        root_category_id
        secure_base_link_url
        secure_base_media_url
        secure_base_static_url
        secure_base_url
        show_cms_breadcrumbs
        cookie {
            cookie_lifetime
            cookie_path
            cookie_domain
            cookie_secure
        }
        stripe_mode
        stripe_test_pk
        stripe_live_pk
    }
    currency {
        available_currency_codes
        base_currency_code
        base_currency_symbol
        exchange_rates {
            currency_to
            rate
        }
    }
    countries {
        full_name_locale
        id
        two_letter_abbreviation
        available_regions {
            code
            id 
            name
        }
    }
}